### ISSUE TITLE
Logitech G Pro Wireless Superlight not detect when wireless.

### ISSUE THREAD

**Issue by ethannij** [libratbag/libratbag#1333]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.16
- Distribution:  Gentoo
- Kernel version (ex. `uname -srmo`): Linux 5.15.52-gentoo x86_64 GNU/Linux

**Describe the bug**
When I launch piper, no device is detected. ratbagctl does not see any devices either. I have to plug my mouse in with a cable (as opposed to using it wirelessly with the receiver) in order to access the settings for it. The settings seem to apply to the mouse just fine, i just cannot configure them without plugging it in.

**To Reproduce**
1. Connect Micro USB cable into dongle
2. Turn the mouse on
3. type `ratbagctl list`
5. See error

**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
[OUTPUT HERE](https://pastebin.com/dQfjdbfT)
```

**Comment by ethannij** [comment]
quick update, i tried solaar, and the mouse is detected fine when wireless, so i think it's a detection problem with libratbag and not with my own configuration.

**Comment by Neburski** [comment]
Today, I received my Logitech G Pro Wireless Superlight and I can confirm this issue. The mouse itself works perfect, but to configure it with libratbag / piper, it is necessary to connect it with the USB cable. 

Solaar allows to configure it while using the mouse wireless, but Solaar doesn't support saving a profile to the onboard memory. I merely mention Solaar here as a double check that it is possible to configure the mouse wireless.

### My System

OS: Arch Linux
libratbag version: 0.16 (both `ratbagd --version` and `ratbagctl --version`
piper version: 0.6 (from GUI)

### Using the mouse wireless

The device can be seen and configured by Solaar (v1.1.4) out of the box, but libratbag doesn't see the device, it can only detect the receiver.

Output of `lsusb`:
```
$ lsusb
... # Removed non-logitech related output.
Bus 001 Device 016: ID 046d:c547 Logitech, Inc. USB Receiver
... # Removed non-logitech related output.
```
It only displays information on the USB receiver.

Output from `sudo ratbagd --verbose`:
```
$ sudo ratbagd --verbose
Initializing libratbag
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: 046d:c547 is a Logitech receiver, not a device. Ignoring...
... # Removed non-logitech related output.
DBus server ready
```

```
$ ratbagctl
No devices available.
```

### Using the mouse with USB cable

The mouse can be configured through piper and the profile can be saved on the mouse.

Output of `lsusb`:
```
$ lsusb
... # Removed non-logitech related output.
Bus 001 Device 019: ID 046d:c094 Logitech, Inc. PRO X Wireless   #  <--- This is missing when working wireless.
... # Removed non-logitech related output.
Bus 001 Device 016: ID 046d:c547 Logitech, Inc. USB Receiver
... # Removed non-logitech related output.
```

Output from `sudo ratbagd` (using non-verbose output):
```
$ sudo ratbagd
hidraw9: "Logitech PRO X Wireless", 5 profiles
```

Output from `ratbagctl`:
`screaming-acouchy:   Logitech PRO X Wireless`

**Comment by fluffynuts** [comment]
I get the same result with the G Pro (not superlight)

**Comment by Laminaat** [comment]
Same results on Fedora 36. Shows up wired, but not when connected wireless with the USB Receiver.

Potentially some interesting findings in this Solaar Issue:
https://github.com/pwr-Solaar/Solaar/issues/1305

**Comment by Vitchuu** [comment]
I'm having this exact same issue. Plugging it in with the wire, configuring it then and then going back to wireless seems to work for DPI but it can't change any button input binds, even while in wired mode.

It'll say it has changed it successfully, but doesn't actually change anything unless I'm trying to put a mouse button to the super key (Meta, windows key, whatever you want to call it.) doesn't work and says something has gone wrong.
If it helps, I'm running Fedora Linux 37 with Gnome Wayland.

**Comment by amfern** [comment]
The c547 lightspeed receiver is unsupported in the kernel, therefore libratbag cannot access the devices connected to the receiver.
This issue is tracked on https://github.com/libratbag/libratbag/issues/1178

**Comment by adrfantini** [comment]
Is this still relevant?

I've seen [reports](https://github.com/libratbag/libratbag/issues/1488#issuecomment-1807102241) that this is fixed on newer kernels, but personally my g502x still does not work for me on the latest Arch vanilla kernel

**Comment by DonKatsu** [comment]
I'm on Kernel 6.7.5 and Piper still shows "Cannot find any devices" when my GPX is connected wirelessly.

**Comment by goatedpenguin** [comment]
I have this issue too are there any fixes yet?

**Comment by alcon678** [comment]
I have the same issue with g502 x plus wired and wireless mode, and with MX3s too
They do not show in Solaar nor in Piper

`sudo ratbagd --verbose=raw `shows the Logitech receiver and the Logitech G502 X PLUS but `ratbagctl list`  shows No devices available.
I'm on Fedora 39 with 6.7.7-200.fc39.x86_64 kernel

**Comment by Kskis** [comment]
On OpenSUSE TW, Kernel 6.8 still not finding on wired or wireless with Piper.

**Comment by ParetoOptimalDev** [comment]
Same on NixOS unstable with 6.9.1-zen1. 

However, it's likely that there is a failure happening because of https://github.com/NixOS/nixpkgs/pull/312411 before that.

I'll test again after that fix is merged.

**Comment by danir-de** [comment]
Under Arch with Kernel 6.10 (rc) its still the same problem while the Logitech G502 X PLUS is in wireless mode.
`Logitech USB Receiver` is recognized in the `sudo ratbagd --verbose=raw`-output but `ratbagctl list` remains empty.

When connecting via cable, it recognizes the model `Logitech G502 X PLUS`, but won't find any data file for `046d:c095`.

**Comment by goatedpenguin** [comment]
Guys I figured how to solve this for logitech devices(I tried this on arch linux 64 bit iirc):
simply run the command you need with sudo privs:

for devices using the hid++ protocol
`# modprobe hid-logitech-hidpp `

for devices using the unifying receiver(this is the one for most gaming mouses with a dongle iirc)
`# modprobe hid-logitech-dj`

for older logitech devices you need to do this:
`# modprobe hid-logitech`

Choose the right module for your mouse. 
Sorry for the very late reply, hope this helps.

**Comment by malik-rieder** [comment]
> for devices using the hid++ protocol `# modprobe hid-logitech-hidpp `
> 
> for devices using the unifying receiver(this is the one for most gaming mouses with a dongle iirc) `# modprobe hid-logitech-dj`
> 
> for older logitech devices you need to do this: `# modprobe hid-logitech`

This does not work for me on Fedora 41.
I tried all three of the commands for my Logitech G502X. Restarted the mouse and restarted the PC to no avail.

**Comment by ShayBox** [comment]
> restarted the PC

modprobe is only for the current boot

**Comment by malik-rieder** [comment]
> modprobe is only for the current boot

Thanks for the info, but only turning my mouse off and on again also didn't help.
Is there anything else I should do/could try?
